from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
from typing import Any

from .classes import CLASS_BY_ID, class_mapping
from .catalogs import biome_catalog_summary, catalog_summary, worldgen_summary
from .config import CityGenConfig
from .footprints import FOOTPRINT_KINDS
from .generator import Scene
from .geometry import Point
from .roofs import ROOF_KINDS


def write_ply(
    path: str | Path,
    points: list[Point],
    config: CityGenConfig,
) -> Path:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    include_rgb = config.output.include_rgb
    include_class = config.output.include_class

    with output_path.open("w", encoding="utf-8") as handle:
        handle.write("ply\n")
        handle.write("format ascii 1.0\n")
        handle.write("comment generated by citygen\n")
        handle.write(f"element vertex {len(points)}\n")
        handle.write("property float x\n")
        handle.write("property float y\n")
        handle.write("property float z\n")
        if include_rgb:
            handle.write("property uchar red\n")
            handle.write("property uchar green\n")
            handle.write("property uchar blue\n")
        if include_class:
            handle.write("property int class\n")
        handle.write("end_header\n")
        for point in points:
            fields: list[str] = [
                f"{point.x:.4f}",
                f"{point.y:.4f}",
                f"{point.z:.4f}",
            ]
            if include_rgb:
                fields.extend([str(point.red), str(point.green), str(point.blue)])
            if include_class:
                fields.append(str(point.class_id))
            handle.write(" ".join(fields) + "\n")

    return output_path


def write_metadata(path: str | Path, config: CityGenConfig, scene: Scene, points: list[Point]) -> Path:
    output_path = Path(path)
    metadata_path = output_path.with_suffix(".metadata.json")
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    counts = Counter(point.class_id for point in points)
    footprint_counts = Counter(building.footprint.kind for building in scene.buildings)
    roof_counts = Counter((building.roof.kind if building.roof is not None else "flat") for building in scene.buildings)
    biome_building_counts = Counter(building.biome for building in scene.buildings)
    parcel_biome_counts = Counter(building.biome for building in scene.buildings if building.parcel_id is not None)
    footprint_biome_counts: dict[str, dict[str, int]] = {}
    roof_footprint_counts: dict[str, dict[str, int]] = {}
    roof_biome_counts: dict[str, dict[str, int]] = {}
    for building in scene.buildings:
        by_biome = footprint_biome_counts.setdefault(building.footprint.kind, {})
        by_biome[building.biome] = by_biome.get(building.biome, 0) + 1
        roof_kind = building.roof.kind if building.roof is not None else "flat"
        by_footprint = roof_footprint_counts.setdefault(roof_kind, {})
        by_footprint[building.footprint.kind] = by_footprint.get(building.footprint.kind, 0) + 1
        by_roof_biome = roof_biome_counts.setdefault(roof_kind, {})
        by_roof_biome[building.biome] = by_roof_biome.get(building.biome, 0) + 1
    payload: dict[str, Any] = {
        "seed": config.seed,
        "tile": {
            "x": config.tile.x,
            "y": config.tile.y,
            "bbox": {
                "min_x": scene.bbox.min_x,
                "min_y": scene.bbox.min_y,
                "max_x": scene.bbox.max_x,
                "max_y": scene.bbox.max_y,
            },
        },
        "point_count": len(points),
        "class_counts": {
            CLASS_BY_ID[class_id].name: count for class_id, count in sorted(counts.items())
        },
        "class_mapping": class_mapping(),
        "worldgen": worldgen_summary(),
        "catalogs": catalog_summary(scene.context.catalogs),
        "biome_catalog": biome_catalog_summary(scene.context.catalogs),
        "object_feature_counts": _object_feature_counts(scene, points),
        "road_models": list(scene.road_models),
        "road_profile_counts": scene.road_network.road_profile_counts(),
        "road_profile_counts_by_biome": scene.road_network.road_profile_counts_by_biome(),
        "road_widths": scene.road_network.road_widths(),
        "road_median": scene.road_network.road_median_info(),
        "biome_counts": scene.biome_counts,
        "building_counts": {
            "total": len(scene.buildings),
            "by_footprint": dict(sorted(footprint_counts.items())),
            "by_roof": dict(sorted(roof_counts.items())),
            "by_biome": dict(sorted(biome_building_counts.items())),
            "by_footprint_and_biome": {
                footprint: dict(sorted(by_biome.items()))
                for footprint, by_biome in sorted(footprint_biome_counts.items())
            },
            "by_roof_and_footprint": {
                roof: dict(sorted(by_footprint.items()))
                for roof, by_footprint in sorted(roof_footprint_counts.items())
            },
            "by_roof_and_biome": {
                roof: dict(sorted(by_biome.items()))
                for roof, by_biome in sorted(roof_biome_counts.items())
            },
            "by_parcel_biome": dict(sorted(parcel_biome_counts.items())),
        },
        "parcel_counts": scene.parcel_counts,
        "supported_footprint_types": list(FOOTPRINT_KINDS),
        "supported_roof_types": list(ROOF_KINDS),
        "config": config.to_dict(),
    }
    metadata_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return metadata_path


def _object_feature_counts(scene: Scene, points: list[Point]) -> dict[str, int]:
    class_counts = Counter(point.class_id for point in points)
    class_name_counts = {
        CLASS_BY_ID[class_id].name: count
        for class_id, count in class_counts.items()
        if class_id in CLASS_BY_ID
    }
    return {
        "terrain_surface": class_name_counts.get("ground", 0),
        "road_network": len(scene.road_network.primitives),
        "road_surface": class_name_counts.get("road", 0),
        "road_sidewalk": class_name_counts.get("sidewalk", 0),
        "road_median": class_name_counts.get("road_median", 0),
        "parcel_blocks": scene.parcel_counts.get("blocks", 0),
        "building": len(scene.buildings),
        "building_footprint": len(scene.buildings),
        "building_roof": class_name_counts.get("building_roof", 0),
    }
