from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
from typing import Any

from .classes import CLASS_BY_ID, class_mapping
from .catalogs import biome_catalog_summary, catalog_summary, worldgen_summary
from .config import CityGenConfig
from .fences import FENCE_TYPES
from .footprints import FOOTPRINT_KINDS
from .generator import Scene
from .geometry import Point, angle_delta_degrees, normalize_degrees
from .roofs import ROOF_KINDS


def write_ply(
    path: str | Path,
    points: list[Point],
    config: CityGenConfig,
) -> Path:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    include_rgb = config.output.include_rgb
    include_class = config.output.include_class

    with output_path.open("w", encoding="utf-8") as handle:
        handle.write("ply\n")
        handle.write("format ascii 1.0\n")
        handle.write("comment generated by citygen\n")
        handle.write(f"element vertex {len(points)}\n")
        handle.write("property float x\n")
        handle.write("property float y\n")
        handle.write("property float z\n")
        if include_rgb:
            handle.write("property uchar red\n")
            handle.write("property uchar green\n")
            handle.write("property uchar blue\n")
        if include_class:
            handle.write("property int class\n")
        handle.write("end_header\n")
        for point in points:
            fields: list[str] = [
                f"{point.x:.4f}",
                f"{point.y:.4f}",
                f"{point.z:.4f}",
            ]
            if include_rgb:
                fields.extend([str(point.red), str(point.green), str(point.blue)])
            if include_class:
                fields.append(str(point.class_id))
            handle.write(" ".join(fields) + "\n")

    return output_path


def write_metadata(path: str | Path, config: CityGenConfig, scene: Scene, points: list[Point]) -> Path:
    output_path = Path(path)
    metadata_path = output_path.with_suffix(".metadata.json")
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    counts = Counter(point.class_id for point in points)
    footprint_counts = Counter(building.footprint.kind for building in scene.buildings)
    roof_counts = Counter((building.roof.kind if building.roof is not None else "flat") for building in scene.buildings)
    biome_building_counts = Counter(building.biome for building in scene.buildings)
    parcel_biome_counts = Counter(building.biome for building in scene.buildings if building.parcel_id is not None)
    footprint_biome_counts: dict[str, dict[str, int]] = {}
    roof_footprint_counts: dict[str, dict[str, int]] = {}
    roof_biome_counts: dict[str, dict[str, int]] = {}
    for building in scene.buildings:
        by_biome = footprint_biome_counts.setdefault(building.footprint.kind, {})
        by_biome[building.biome] = by_biome.get(building.biome, 0) + 1
        roof_kind = building.roof.kind if building.roof is not None else "flat"
        by_footprint = roof_footprint_counts.setdefault(roof_kind, {})
        by_footprint[building.footprint.kind] = by_footprint.get(building.footprint.kind, 0) + 1
        by_roof_biome = roof_biome_counts.setdefault(roof_kind, {})
        by_roof_biome[building.biome] = by_roof_biome.get(building.biome, 0) + 1
    payload: dict[str, Any] = {
        "seed": config.seed,
        "tile": {
            "x": config.tile.x,
            "y": config.tile.y,
            "bbox": {
                "min_x": scene.bbox.min_x,
                "min_y": scene.bbox.min_y,
                "max_x": scene.bbox.max_x,
                "max_y": scene.bbox.max_y,
            },
        },
        "point_count": len(points),
        "class_counts": {
            CLASS_BY_ID[class_id].name: count for class_id, count in sorted(counts.items())
        },
        "class_mapping": class_mapping(),
        "worldgen": worldgen_summary(),
        "catalogs": catalog_summary(scene.context.catalogs),
        "biome_catalog": biome_catalog_summary(scene.context.catalogs),
        "object_feature_counts": _object_feature_counts(scene, points),
        "road_models": list(scene.road_models),
        "road_profile_counts": scene.road_network.road_profile_counts(),
        "road_profile_counts_by_biome": scene.road_network.road_profile_counts_by_biome(),
        "road_widths": scene.road_network.road_widths(),
        "road_median": scene.road_network.road_median_info(),
        "biome_counts": scene.biome_counts,
        "building_counts": {
            "total": len(scene.buildings),
            "by_footprint": dict(sorted(footprint_counts.items())),
            "by_roof": dict(sorted(roof_counts.items())),
            "by_biome": dict(sorted(biome_building_counts.items())),
            "by_footprint_and_biome": {
                footprint: dict(sorted(by_biome.items()))
                for footprint, by_biome in sorted(footprint_biome_counts.items())
            },
            "by_roof_and_footprint": {
                roof: dict(sorted(by_footprint.items()))
                for roof, by_footprint in sorted(roof_footprint_counts.items())
            },
            "by_roof_and_biome": {
                roof: dict(sorted(by_biome.items()))
                for roof, by_biome in sorted(roof_biome_counts.items())
            },
            "by_parcel_biome": dict(sorted(parcel_biome_counts.items())),
        },
        "parcel_counts": scene.parcel_counts,
        "fence_counts": scene.fence_counts,
        "parcel_building_alignment": _parcel_building_alignment(config, scene),
        "building_orientations": _building_orientation_summary(scene),
        "block_geometry": _block_geometry_summary(config, scene),
        "parcel_geometry": _parcel_geometry_summary(scene),
        "supported_footprint_types": list(FOOTPRINT_KINDS),
        "supported_roof_types": list(ROOF_KINDS),
        "supported_fence_types": list(FENCE_TYPES),
        "config": config.to_dict(),
    }
    metadata_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return metadata_path


def _object_feature_counts(scene: Scene, points: list[Point]) -> dict[str, int]:
    class_counts = Counter(point.class_id for point in points)
    class_name_counts = {
        CLASS_BY_ID[class_id].name: count
        for class_id, count in class_counts.items()
        if class_id in CLASS_BY_ID
    }
    return {
        "terrain_surface": class_name_counts.get("ground", 0),
        "road_network": len(scene.road_network.primitives),
        "road_surface": class_name_counts.get("road", 0),
        "road_sidewalk": class_name_counts.get("sidewalk", 0),
        "road_median": class_name_counts.get("road_median", 0),
        "parcel_blocks": scene.parcel_counts.get("blocks", 0),
        "building": len(scene.buildings),
        "building_footprint": len(scene.buildings),
        "building_roof": class_name_counts.get("building_roof", 0),
        "parcel_fence": scene.fence_counts.get("segments", 0),
        "fence_foundation": class_name_counts.get("fence_foundation", 0),
    }


def _parcel_building_alignment(config: CityGenConfig, scene: Scene) -> dict[str, Any]:
    parcels_by_id = {parcel.id: parcel for parcel in scene.parcels}
    with_parcel = [building for building in scene.buildings if building.parcel_id is not None]
    tolerance = config.parcels.orientation_jitter_degrees + 1e-6
    aligned = 0
    for building in with_parcel:
        if config.parcels.building_alignment == "global":
            target = 0.0
        else:
            parcel = parcels_by_id.get(building.parcel_id)
            target = parcel.orientation_degrees if parcel is not None else 0.0
        if angle_delta_degrees(building.orientation_degrees, target) <= tolerance:
            aligned += 1

    too_small = 0
    for parcel in scene.parcels:
        if not parcel.buildable:
            continue
        buildable = parcel.buildable_geometry.inset(max(0.0, config.buildings.setback_m * 0.35))
        if buildable is None or min(buildable.width, buildable.depth) < max(4.0, config.buildings.footprint_min_m * 0.5):
            too_small += 1

    return {
        "mode": config.parcels.building_alignment,
        "buildings_with_parcel_id": len(with_parcel),
        "aligned_buildings": aligned,
        "skipped_too_small_parcels": too_small,
        "orientation_jitter_degrees": config.parcels.orientation_jitter_degrees,
        "require_building_inside_buildable_area": config.parcels.require_building_inside_buildable_area,
        "max_building_coverage": config.parcels.max_building_coverage,
    }


def _building_orientation_summary(scene: Scene) -> dict[str, float | int]:
    if not scene.buildings:
        return {
            "min_degrees": 0.0,
            "max_degrees": 0.0,
            "unique_bucket_count": 0,
        }
    values = [normalize_degrees(building.orientation_degrees) for building in scene.buildings]
    buckets = {round(value) % 360 for value in values}
    return {
        "min_degrees": round(min(values), 3),
        "max_degrees": round(max(values), 3),
        "unique_bucket_count": len(buckets),
    }


def _block_geometry_summary(config: CityGenConfig, scene: Scene) -> dict[str, Any]:
    axis_aligned = sum(1 for block in scene.blocks if _is_axis_aligned(block.orientation_degrees))
    oriented = len(scene.blocks) - axis_aligned
    return {
        "oriented_blocks": oriented,
        "axis_aligned_blocks": axis_aligned,
        "orientation_source": config.parcels.block_orientation_source,
        "oriented_blocks_enabled": config.parcels.oriented_blocks,
        "orientation_bucket_degrees": _orientation_buckets(
            block.orientation_degrees for block in scene.blocks
        ),
    }


def _parcel_geometry_summary(scene: Scene) -> dict[str, Any]:
    axis_aligned = sum(1 for parcel in scene.parcels if _is_axis_aligned(parcel.orientation_degrees))
    oriented = len(scene.parcels) - axis_aligned
    return {
        "oriented_parcels": oriented,
        "axis_aligned_parcels": axis_aligned,
        "buildable_area_failures": sum(1 for parcel in scene.parcels if not parcel.buildable),
        "orientation_bucket_degrees": _orientation_buckets(
            parcel.orientation_degrees for parcel in scene.parcels
        ),
    }


def _orientation_buckets(values) -> dict[str, int]:
    counts: Counter[int] = Counter(round(normalize_degrees(value)) % 360 for value in values)
    return {str(bucket): count for bucket, count in sorted(counts.items())}


def _is_axis_aligned(angle_degrees: float) -> bool:
    angle = normalize_degrees(angle_degrees) % 90.0
    return min(angle, 90.0 - angle) <= 1e-6
